project:
  type: website
  output-dir: docs

website:
  title: "Shota Tachibana"
  favicon: favicon.png
  google-analytics: "G-ZD4MJZ2MYG"
  navbar:
    tools:
      - icon: github
        href: https://github.com/shotatachibana
      - icon: linkedin
        href: https://www.linkedin.com/in/shota-tachibana-75729b41b/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Bb83kBkogRxm%2BNeuLub37Kw%3D%3D        
    left:
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: https://shotatachibana.github.io/tips/a_intro.html
        text: "(Tips)"
  page-footer: "Copyright 2025, Shota Tachibana"

format:
  html:
    theme:
      - cosmo
      - brand
    css:
      - styles.css
      - japanese-font.css
    toc: true



