project:
  type: website
  output-dir: docs

website:
  title: "Shota Tachibana"
  google-analytics: "G-ZD4MJZ2MYG"
  navbar:
    left:
      - href: index.qmd
        text: ABOUT
      - href: publications.qmd
        text: PUBLICATIONS
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



