project:
  type: website
  output-dir: docs

website:
  title: "Shota Tachibana"
  google-analytics: "G-ZD4MJZ2MYG"
  navbar:
    tools:
      - icon: github
        href: https://github.com/shotatachibana
    left:
      - href: index.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: https://shotatachibana.github.io/tips/
        text: "(Tips for me)"
  page-footer: "Copyright 2025, Shota Tachibana"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



