project:
  type: website
  output-dir: docs

website:
  title: "Shota Tachibana"
  google-analytics: "G-ZD4MJZ2MYG"
  navbar:
    left:
      - href: index.qmd
        text: ABOUT
      - href: publications.qmd
        text: PUBLICATIONS
      - href: tips.qmd
        text: TIPS

website:
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, source, issue]  

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



