project:
  type: website
  output-dir: docs

website:
  title: "shotatachibana.github.io"
  google-analytics: "G-ZD4MJZ2MYG"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



